In [1]:
import pandas as pd
from pandas import to_datetime
import datetime

import geopy
from geopy import GoogleV3
from keys import g_key
geolocator = GoogleV3(api_key=g_key)
import googlemaps
gmaps = googlemaps.Client(key=g_key)

import requests
import json

In [2]:
new_df = pd.read_csv('Cosmetologists.csv', header=1)

In [3]:
new_df

,FIRSTNAME,LASTNAME,ADDRESS1,ADDRESS2,CITY,State Code,ZIPCODE,LIC TYPE CODE,LICENSENUM,DATEOFEXPIRY,LIC STATUS CODE
0,Johnette,Bowling,4252 Mitchell Estate St.,NaN,Sophia,NC,27350,C,55855.0,10/1/22,E
1,Melody,Jefferson,2707-A Bluff View Drive,NaN,Greenville,NC,27834,C,94904.0,10/1/22,A
2,Ignacio,Quezada-Mendoza,NaN,NaN,NaN,NaN,NaN,C,108424.0,10/1/23,A
3,Aleksandra,Khudina,16e mansion woods,NaN,Agawam,MA,01001,C,108299.0,10/1/23,A
4,Natalie,Sharac,6 Kylene circle,NaN,Southampton,MA,01073,C,117017.0,10/1/23,A
...,...,...,...,...,...,...,...,...,...,...,...
79618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79620,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

new_df = new_df.rename(columns={'FIRSTNAME':'First Name', 'LASTNAME':'Last Name'})
new_df = new_df.drop(columns='ADDRESS2')
new_df = new_df.dropna()
new_df = new_df.rename(columns={'ADDRESS1': 'Address', 'CITY':'City', 'State Code': 'State', 'ZIPCODE':'Zip', 'LIC TYPE CODE':'License Code', 'DATEOFEXPIRY':'Expiration Date'})
new_df = new_df.rename(columns={'LICENSENUM': 'License Number', 'LIC STATUS CODE': 'License Status Code'})
nc_df = new_df.loc[new_df['State'] == 'NC']
nc_df = nc_df.reset_index(inplace=True)

## Checking for Duplicates
nc_df.drop_duplicates()

nc_df['Expiration Date'] = pd.to_datetime(nc_df['Expiration Date'])

nc_df_2021 = nc_df[nc_df['Expiration Date'].dt.year == 2021]
nc_df_2022 = nc_df[nc_df['Expiration Date'].dt.year == 2022]
nc_df_2023 = nc_df[nc_df['Expiration Date'].dt.year == 2023]
nc_df_2021 = nc_df_2021.reset_index(inplace=True)
nc_df_2022 = nc_df_2022.reset_index(inplace=True)
nc_df_2023 = nc_df_2023.reset_index(inplace=True)

new_nc_df = nc_df_2021.append(nc_df_2022)
new_nc_df = new_nc_df.append(nc_df_2023)
new_nc_df = new_nc_df.reset_index()
new_nc_df = new_nc_df.drop(columns = ['index', 'level_0'])
new_nc_df

sc_df = new_df.loc[new_df['State'] == 'SC']
sc_df = sc_df.reset_index(inplace=True)
sc_df.drop_duplicates()

sc_df['Expiration Date'] = pd.to_datetime(sc_df['Expiration Date'])

sc_df_2021 = sc_df[sc_df['Expiration Date'].dt.year == 2021]
sc_df_2022 = sc_df[sc_df['Expiration Date'].dt.year == 2022]
sc_df_2023 = sc_df[sc_df['Expiration Date'].dt.year == 2023]
sc_df_2021 = sc_df_2021.reset_index(inplace=True))
sc_df_2022 = sc_df_2022.reset_index(inplace=True))
sc_df_2023 = sc_df_2023.reset_index(inplace=True))

new_sc_df = sc_df_2021.append(sc_df_2022)
new_sc_df = new_sc_df.append(sc_df_2023)
new_sc_df = new_sc_df.reset_index()
new_sc_df = new_sc_df.drop(columns = ['index', 'level_0'])
new_sc_df

del nc_df
del sc_df
nc_df = new_nc_df
sc_df = new_sc_df

nc_df['Full Address'] = nc_df['Address']  + ' ' + nc_df['City'] + ' ' + nc_df['State']
sc_df['Full Address'] = sc_df['Address']  + ' ' + sc_df['City'] + ' ' + sc_df['State']

nc_df['Latitude'] = ""
nc_df['Longitude'] = ""
nc_lat = []
nc_lng = []
nc_addresses = nc_df['Full Address'].tolist()

sc_df['Latitude'] = ""
sc_df['Longitude'] = ""
sc_lat = []
sc_lng = []
sc_addresses = sc_df['Full Address'].tolist()

nc_df.to_csv('north_carolina.csv', index=False, header=True)
sc_df.to_csv('south_carolina.csv', index=False, header=True)

nc_df["loc"] = nc_df["Full Address"].apply(geolocator.geocode)
nc_df["point"]= nc_df["loc"].apply(lambda loc: tuple(loc.point) if loc else None)
nc_df[['Latitude', 'Longitude', 'Altitude']] = pd.DataFrame(nc_df['point'].to_list(), index=nc_df.index)
nc_df = nc_df.drop(columns=['loc', 'point', 'Altitude'])

locations = sc_df[["Latitude", "Longitude"]].astype(float)
locations_2 = nc_df[["Latitude", "Longitude"]].astype(float)

sc_df["loc"] = sc_df["Full Address"].apply(geolocator.geocode)
sc_df["point"]= sc_df["loc"].apply(lambda loc: tuple(loc.point) if loc else None)
sc_df[['Latitude', 'Longitude', 'Altitude']] = pd.DataFrame(sc_df['point'].to_list(), index=sc_df.index)
sc_df = sc_df.drop(columns=['loc', 'point', 'Altitude'])

huntersville_df = nc_df.loc[nc_df['City'] == 'Huntersville']
huntersville_df = huntersville_df.reset_index(inplace=True)
huntersville_df.to_csv('huntersville.csv', index=False, header=True)

concord_df = nc_df.loc[nc_df['City'] == 'Concord']
concord_df = concord_df.reset_index(inplace=True)
concord_df.to_csv('concord.csv', index=False, header=True)

gastonia_df = nc_df.loc[nc_df['City'] == 'Gastonia']
gastonia_df = gastonia_df.reset_index(inplace=True)
gastonia_df.to_csv('gastonia.csv', index=False, header=True)

matthews_df = nc_df.loc[nc_df['City'] == 'Matthews']
matthews_df = matthews_df.reset_index(inplace=True)
matthews_df.to_csv('matthews.csv', index=False, header=True)

kannapolis_df = nc_df.loc[nc_df['City'] == 'Kannapolis']
kannapolis_df = kannapolis_df.reset_index(inplace=True)
kannapolis_df.to_csv('kannapolis.csv', index=False, header=True)

nc_df = pd.DataFrame(None)

In [4]:
nc_df = pd.read_csv('north_carolina.csv', names=['First Name', 'Last Name', 'Address', 'City', 'State', 'Zip', 'License Code', 'License Number', 'Expiration Date', 'License Status Code', 'Full Address', 'Latitude', 'Longitude'])
sc_df = pd.read_csv('south_carolina.csv', names=['First Name', 'Last Name', 'Address', 'City', 'State', 'Zip', 'License Code', 'License Number', 'Expiration Date', 'License Status Code', 'Full Address', 'Latitude', 'Longitude'])

In [5]:
nc_df['City'] = nc_df['City'].str.title()
sc_df['City'] = sc_df['City'].str.title()
nc_df['Address'] = nc_df['Address'].str.title()
sc_df['Address'] = sc_df['Address'].str.title()
nc_df['Full Address'] = nc_df['Full Address'].str.title()
sc_df['Full Address'] = sc_df['Full Address'].str.title()

nc_df.to_csv('north_carolina.csv', index=False, header=True)
sc_df.to_csv('south_carolina.csv', index=False, header=True)

In [6]:
charlotte_df = nc_df.loc[nc_df['City'] == 'Charlotte']
charlotte_df = charlotte_df.reset_index()
charlotte_df = charlotte_df.drop(columns=['index'])
charlotte_df.to_csv('charlotte.csv', index=False, header=True)

In [7]:
charlotte_df['First Name'] = charlotte_df['First Name'].str.title()
charlotte_df['Last Name'] = charlotte_df['Last Name'].str.title()
charlotte_df.rename(columns={'First Name':'First_Name', 'Last Name':'Last_Name'}, inplace=True)
charlotte_df['Address'] = charlotte_df['Address'].str.title()
charlotte_df['Zip'] = charlotte_df['Zip'][:5]
charlotte_df['Zip'] = charlotte_df['Zip'].astype('str')
charlotte_df['Address'] = charlotte_df['Address'].str.replace(r'[^\w\s]+', '')
charlotte_df["Address"]= charlotte_df['Address'].str.replace(' STREET', ' ST')
charlotte_df["Address"]= charlotte_df['Address'].str.replace(' BOULEVARD', ' BLVD')
charlotte_df["Address"]= charlotte_df['Address'].str.replace(' COURT', " CT")
charlotte_df["Address"]= charlotte_df['Address'].str.replace(' ROAD', ' RD')
charlotte_df["Address"]= charlotte_df['Address'].str.replace(' LANE', ' LN')
charlotte_df["Address"]= charlotte_df['Address'].str.replace(' PLACE', ' PL')

/var/folders/jm/4cwpb48s6xv_vgw8y_7bdnn80000gn/T/ipykernel_27012/1951923709.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  charlotte_df['Address'] = charlotte_df['Address'].str.replace(r'[^\w\s]+', '')

## Testing out finding the distance from each address to the target salon ##

lat_lng_list = charlotte_df[['Latitude', 'Longitude']].values.tolist()

carmen_address = '324 S Sharon Amity Rd Charlotte NC'
geo_code = geolocator.geocode(carmen_address)

distance = gmaps.distance_matrix([str(lat_lng_list[0][0]) + " " + str(lat_lng_list[0][1])], [str(geo_code[1][0]) + " " + str(geo_code[1][1])], mode='driving', units='imperial')['rows'][0]['elements'][0]

# distance['distance']['text']
geo_code[1][0]

miles_list = []

for i in range(len(charlotte_df)):
    distance = gmaps.distance_matrix([str(lat_lng_list[i][0]) + " " + str(lat_lng_list[i][1])], [str(geo_code[1][0]) + " " + str(geo_code[1][1])], mode='driving', units='imperial')['rows'][0]['elements'][0]
    geocode_list = distance['distance']['text']
    miles_list.append(geocode_list)

In [8]:
charlotte_df

,First_Name,Last_Name,Address,City,State,Zip,License Code,License Number,Expiration Date,License Status Code,Full Address,Latitude,Longitude
0,Huong Nguyen,Dinh,9505 Seamill Rd,Charlotte,NC,28278,C,74484.0,2021-10-01,A,9505 Seamill Rd Charlotte Nc,35.1653988,-80.99632319999999
1,Justin,Flournoy,2229 Village Lake Dr,Charlotte,NC,27212,C,111314.0,2021-10-01,A,2229 Village Lake Dr. Charlotte Nc,35.161911,-80.74212399999999
2,Joanne E,Reeves,2000 Paladin Ct,Charlotte,NC,28012,C,102939.0,2021-10-01,A,2000 Paladin Ct Charlotte Nc,35.2507416,-81.0495641
3,Lamont,Cary,2000 South Blvd,Charlotte,NC,28023,C,112918.0,2021-10-01,A,2000 South Blvd. Charlotte Nc,35.20955,-80.86048129999999
4,Bao,Yang,2915 Phillips Fairway Dr,Charlotte,NC,28031,C,61245.0,2021-10-01,A,2915 Phillips Fairway Dr Charlotte Nc,35.3347486,-80.90145919999999
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,Sharell,Daley,12820 Winter Hazel Rd Apt 208,Charlotte,NC,nan,C,109087.0,2023-10-01,A,12820 Winter Hazel Rd. Apt 208 Charlotte Nc,35.10455,-80.99669999999999
4916,Kristy,Harrison,P O Box 16861,Charlotte,NC,nan,C,57650.0,2023-10-01,A,P. O. Box 16861 Charlotte Nc,35.2270869,-80.8431267
4917,Latrea,Ricks,316 North Rhett Street,Charlotte,NC,nan,C,118704.0,2023-10-01,A,316 North Rhett Street Charlotte Nc,33.9226857,-78.017153
4918,Yfaina,Diaz,7800 Royal Point Dr Apt 104,Charlotte,NC,nan,C,97747.0,2023-10-01,A,7800 Royal Point Dr Apt 104 Charlotte Nc,35.14524,-80.92376
4919,Kiarra,Grant,6908 Dixie River Rd,Charlotte,NC,nan,C,117298.0,2023-10-01,A,6908 Dixie River Rd. Charlotte Nc,35.1773446,-80.9908413

# charlotte_df['Miles_Away'] = miles_list
# charlotte_df = charlotte_df.drop(columns=['Latitude', 'Longitude'])
# charlotte_df['Last_Name'] = charlotte_df['Last_Name'].str.title()
# charlotte_df['Expiration Date'] = pd.to_datetime(charlotte_df['Expiration Date'])
# charlotte_df_2022 = charlotte_df[charlotte_df['Expiration Date'].dt.year == 2022]
# charlotte_df_2023 = charlotte_df[charlotte_df['Expiration Date'].dt.year == 2023]
charlotte_df_2022.to_csv('charlotte_df_2022.csv', index=False, header=True)
charlotte_df_2023.to_csv('charlotte_df_2023.csv', index=False, header=True)

In [9]:
charlotte_df = pd.read_csv('charlotte_df_2022.csv')
charlotte_df_2 = pd.read_csv('charlotte_df_2023.csv')

In [10]:
frames = [charlotte_df, charlotte_df_2]
new_charlotte = pd.concat(frames)
# new_charlotte = new_charlotte.drop(columns=['Latitude', 'Longitude'])
new_charlotte = new_charlotte.drop(columns='Zip')
new_charlotte = new_charlotte.sort_values(by=['Miles_Away'])
new_charlotte = new_charlotte.reset_index(drop=True)
new_charlotte['First_Name'] = new_charlotte['First_Name'].str.title()
new_charlotte.to_csv('new_charlotte.csv', index=True, header=True)

In [11]:
new_df = new_charlotte.drop(columns=['License Number', 'Expiration Date', 'License Status Code', 'Full Address'])
new_df.to_csv('new_df.csv', index=False, header=True)

In [12]:
new_df = new_df.astype(str)
new_df.First_Name.dtypes

dtype('O')

new_df = pd.DataFrame()
new_df["Names"] = new_charlotte.First_Name + (' ') + new_charlotte.Last_Name
names_list = []
names_list.extend(new_df.Names)
# names_list

names_list[0]

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait

service = Service(executable_path=ChromeDriverManager().install())
d = webdriver.Chrome(service=service)

d.get('https://www.instagram.com')
d.implicitly_wait(5)
# element = WebDriverWait(d, 30).until(element_to_be_clickable((By.NAME, "username")))
username_input = d.find_element(By.NAME, "username")
username_input.send_keys("cursiveinkwells@gmail.com")

password_input = d.find_element(By.NAME, "password")
password_input.send_keys("Ruger2012!?")

d.find_element(By.XPATH, "//button[contains(.,'Log In')]").click()
# login_button.click()
d.implicitly_wait(5)
d.find_element(By.XPATH, "//button[contains(.,'Not Now')]").click()
searchbox = d.find_element(By.XPATH, "//input[@placeholder='Search']")
searchbox.clear()

# for names in names_list:
searchbox.send_keys(names_list[0])
e.send_keys(Keys.ENTER)
#scrape page here